#!/bin/bash
#
# Copyright © 2016 Yannick Loiseau <me@yloiseau.net>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#

case $1 in
    -h|--help) 
        cat <<EOC
Watson status for I3 (conky).

Save in e.g. ~/.config/i3/watson-status and add
{"full_text": "\${texeci 5 ~/.config/i3/watson-status}"}
to your conky config file.
EOC
esac

watson status |
sed -r '
    s!^Project !!g;
    s!(.+)\s+started !\1 (!g;
    s! ago .*!)!g
    '


