#!/bin/bash
#
# Copyright © 2016 Yannick Loiseau <me@yloiseau.net>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#

watson status |
sed -r '
    s!^Project !!g;
    s!([^ ]+).+started !\1 (!g;
    s! ago .*!)!g
    '


