#!/bin/bash
#
# Copyright © 2016 Yannick Loiseau <me@yloiseau.net>
# This work is free. You can redistribute it and/or modify it under the
# terms of the Do What The Fuck You Want To Public License, Version 2,
# as published by Sam Hocevar. See http://www.wtfpl.net/ for more details.
#

set -e

nbmonth=${1:-12}; shift

seq $nbmonth -1 1 | while read m ; do
    watson report \
        -f $(date -d "$m month ago" +%Y-%m) \
        -t $(date -d "$((m-1)) month ago" +%Y-%m) \
        "$@"
done
